# Retail Sales Analytics

## Phase 1: Data Understanding

### Objective
The objective of this notebook is to understand the structure, quality, and characteristics of the retail sales dataset before performing data cleaning and exploratory data analysis.

In [2]:
import numpy as np
import pandas as pd

In [3]:
sales = pd.read_csv(r'D:\Projects\Retail Sales Analytics\Sales_csv.csv')
sales.head()
sales.tail()
sales.sample(5)

,Row ID,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Country,City,...,Postal Code,Region,Product ID,Category,Sub-Category,Product Name,Sales,Quantity,Discount,Profit
6689,4664,CA-2016-111409,18-Sep-16,22-Sep-16,Standard Class,PO-18850,Patrick O'Brill,Consumer,United States,Jacksonville,...,32216,South,OFF-LA-10002787,Office Supplies,Labels,Avery 480,3.000,1,0.2,1.0500
5534,9430,CA-2015-166219,28-Aug-15,01-Sep-15,Standard Class,BP-11185,Ben Peterman,Corporate,United States,Dallas,...,75081,Central,TEC-PH-10004165,Technology,Phones,Mitel MiVoice 5330e IP Phone,1099.960,5,0.2,82.4970
5193,8017,US-2014-131870,09-Sep-14,11-Sep-14,First Class,NF-18595,Nicole Fjeld,Home Office,United States,Lancaster,...,43130,East,FUR-FU-10002501,Furniture,Furnishings,Nu-Dell Executive Frame,60.672,6,0.2,12.8928
8652,3389,CA-2017-148404,07-Oct-17,11-Oct-17,Standard Class,Dp-13240,Dean percer,Home Office,United States,Charlotte,...,28205,South,OFF-BI-10002854,Office Supplies,Binders,"Performers Binder/Pad Holder, Black",50.454,6,0.7,-33.6360
854,6065,CA-2015-111780,25-Dec-15,30-Dec-15,Second Class,RA-19285,Ralph Arnett,Consumer,United States,San Diego,...,92037,West,OFF-PA-10001667,Office Supplies,Paper,Great White Multi-Use Recycled Paper (20Lb. an...,17.940,3,0.0,8.0730

Number of rows

In [4]:
print("Number of rows:", sales.shape[0])

Number of rows: 9994

Number of columns

In [5]:
print("Number of Columns:", sales.shape[1])

Number of Columns: 21

Column names and Data types

In [6]:
print("Column names and their data types:")
print("----------------------------------")
sales.info()
print("----------------------------------")

Column names and their data types:
----------------------------------
<class 'pandas.DataFrame'>
RangeIndex: 9994 entries, 0 to 9993
Data columns (total 21 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Row ID         9994 non-null   int64
 1   Order ID       9994 non-null   str
 2   Order Date     9994 non-null   str
 3   Ship Date      9994 non-null   str
 4   Ship Mode      9994 non-null   str
 5   Customer ID    9994 non-null   str
 6   Customer Name  9994 non-null   str
 7   Segment        9994 non-null   str
 8   Country        9994 non-null   str
 9   City           9994 non-null   str
 10  State          9994 non-null   str
 11  Postal Code    9994 non-null   int64
 12  Region         9994 non-null   str
 13  Product ID     9994 non-null   str
 14  Category       9994 non-null   str
 15  Sub-Category   9994 non-null   str
 16  Product Name   9994 non-null   str
 17  Sales          9994 non-null   float64
 18  Quantity       9994 non-null   int64
 19  Discount       9994 non-null   float64
 20  Profit         9994 non-null   float64
dtypes: float64(3), int64(3), str(15)
memory usage: 1.6 MB
----------------------------------

Missing values

In [7]:
print("Missing Values in each Column")
print("-----------------------------")
print(sales.isnull().sum())
print("-----------------------------")

Missing Values in each Column
-----------------------------
Row ID           0
Order ID         0
Order Date       0
Ship Date        0
Ship Mode        0
Customer ID      0
Customer Name    0
Segment          0
Country          0
City             0
State            0
Postal Code      0
Region           0
Product ID       0
Category         0
Sub-Category     0
Product Name     0
Sales            0
Quantity         0
Discount         0
Profit           0
dtype: int64
-----------------------------

Duplicate rows

In [8]:
print("Duplicate Rows:", sales.duplicated().sum())

Duplicate Rows: 0

Numerical columns

In [9]:
print("\nNumerical Columns:")
print(sales.select_dtypes(include='number').columns)

Numerical Columns:
Index(['Row ID', 'Postal Code', 'Sales', 'Quantity', 'Discount', 'Profit'], dtype='str')

Categorical columns

In [10]:
print("\nCategorical Columns:")
print(sales.select_dtypes(include=['object', 'string']).columns)

Categorical Columns:
Index(['Order ID', 'Order Date', 'Ship Date', 'Ship Mode', 'Customer ID',
       'Customer Name', 'Segment', 'Country', 'City', 'State', 'Region',
       'Product ID', 'Category', 'Sub-Category', 'Product Name'],
      dtype='str')

Memory usage

In [11]:
print("Memory Usage of each columns in bytes:")
print(sales.memory_usage(deep=True))
print("\nTotal Memory usage in MB:", sales.memory_usage(deep=True).sum() / (1024**2))

Memory Usage of each columns in bytes:
Index               132
Row ID            79952
Order ID         629622
Order Date       579652
Ship Date        579652
Ship Mode        617860
Customer ID      569658
Customer Name    622082
Segment          578027
Country          619628
City             582957
State            574527
Postal Code       79952
Region           538271
Product ID       639616
Category         617655
Sub-Category     561580
Product Name     879744
Sales             79952
Quantity          79952
Discount          79952
Profit            79952
dtype: int64

Total Memory usage in MB: 9.22238826751709

General Discription of Data Set

In [12]:
sales.describe()

,Row ID,Postal Code,Sales,Quantity,Discount,Profit
count,9994.000000,9994.000000,9994.000000,9994.000000,9994.000000,9994.000000
mean,4997.500000,55190.379428,229.858001,3.789574,0.156203,28.656896
std,2885.163629,32063.693350,623.245101,2.225110,0.206452,234.260108
min,1.000000,1040.000000,0.444000,1.000000,0.000000,-6599.978000
25%,2499.250000,23223.000000,17.280000,2.000000,0.000000,1.728750
50%,4997.500000,56430.500000,54.490000,3.000000,0.200000,8.666500
75%,7495.750000,90008.000000,209.940000,5.000000,0.200000,29.364000
max,9994.000000,99301.000000,22638.480000,14.000000,0.800000,8399.976000

In [13]:
sales.describe(include='str')

,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Country,City,State,Region,Product ID,Category,Sub-Category,Product Name
count,9994,9994,9994,9994,9994,9994,9994,9994,9994,9994,9994,9994,9994,9994,9994
unique,5009,1237,1334,4,793,793,3,1,531,49,4,1862,3,17,1850
top,CA-2017-100111,05-Sep-16,16-Dec-15,Standard Class,WB-21850,William Brown,Consumer,United States,New York City,California,West,OFF-PA-10001970,Office Supplies,Binders,Staple envelope
freq,14,38,35,5968,37,37,5191,9994,915,2001,3203,19,6026,1523,48

## Initial Observations

- The dataset contains **9,994 records** and **21 columns**.
- There are **no missing values**, indicating high data completeness.
- There are **no duplicate records**.
- `Order Date` and `Ship Date` are currently stored as objects and should be converted to datetime.
- `Sales`, `Profit`, `Discount`, and `Quantity` are numerical features.
- `Postal Code`, although numeric, represents geographical information and will be treated as a categorical feature.
- The dataset appears clean and is ready for the data cleaning and preprocessing phase.