# Retail Sales Analytics
## Phase 2: Data Cleaning
### Perform checks such as:
- Remove duplicates 
- Handle missing values 
- Convert date columns 
- Fix inconsistent category names 
- Check for negative quantities 
- Check negative profits 
- Check impossible discounts 
- Verify unique IDs

In [63]:
import numpy as np
import pandas as pd
sales = pd.read_csv(r'D:\Data Analytics Projects\Retail Sales Analytics\Data\Raw Data\Sales_csv.csv')
sales.head()

,Row ID,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Country,City,...,Postal Code,Region,Product ID,Category,Sub-Category,Product Name,Sales,Quantity,Discount,Profit
0,43,CA-2016-101343,17-Jul-16,22-Jul-16,Standard Class,RA-19885,Ruben Ausman,Corporate,United States,Los Angeles,...,90049,West,OFF-ST-10003479,Office Supplies,Storage,"Eldon Base for stackable storage shelf, platinum",77.88,2,0.0,3.8940
1,514,CA-2017-163405,21-Dec-17,25-Dec-17,Standard Class,BN-11515,Bradley Nguyen,Consumer,United States,Los Angeles,...,90049,West,OFF-AR-10003811,Office Supplies,Art,Newell 327,6.63,3,0.0,1.7901
2,515,CA-2017-163405,21-Dec-17,25-Dec-17,Standard Class,BN-11515,Bradley Nguyen,Consumer,United States,Los Angeles,...,90049,West,OFF-AR-10001246,Office Supplies,Art,Newell 317,5.88,2,0.0,1.7052
3,1606,US-2016-115819,19-Apr-16,24-Apr-16,Second Class,JO-15280,Jas O'Carroll,Consumer,United States,Los Angeles,...,90049,West,OFF-AR-10000823,Office Supplies,Art,Newell 307,5.46,3,0.0,1.5288
4,1607,US-2016-115819,19-Apr-16,24-Apr-16,Second Class,JO-15280,Jas O'Carroll,Consumer,United States,Los Angeles,...,90049,West,OFF-AR-10004456,Office Supplies,Art,Panasonic KP-4ABK Battery-Operated Pencil Shar...,73.20,5,0.0,21.2280

Remove Duplicate rows

In [64]:
sales.duplicated().sum()
# no duplicate rows found

np.int64(0)

Missing values

In [65]:
print("Missing values per column:")
sales.isnull().sum()

Missing values per column:

Row ID           0
Order ID         0
Order Date       0
Ship Date        0
Ship Mode        0
Customer ID      0
Customer Name    0
Segment          0
Country          0
City             0
State            0
Postal Code      0
Region           0
Product ID       0
Category         0
Sub-Category     0
Product Name     0
Sales            0
Quantity         0
Discount         0
Profit           0
dtype: int64

Date Column Handeling

In [66]:
sales['Order Date'] = pd.to_datetime(sales['Order Date'], format='%d-%m-%Y', errors='coerce')
sales['Ship Date'] = pd.to_datetime(sales['Ship Date'], format='%d-%m-%Y', errors='coerce')

In [67]:
sales.sample()

,Row ID,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Country,City,...,Postal Code,Region,Product ID,Category,Sub-Category,Product Name,Sales,Quantity,Discount,Profit
528,5700,CA-2017-148320,NaT,NaT,Standard Class,PG-18895,Paul Gonzalez,Consumer,United States,San Francisco,...,94109,West,OFF-PA-10003022,Office Supplies,Paper,Xerox 1992,35.88,6,0.0,17.5812

Fixing inconsistent category names

In [68]:
categorical_cols = [
    'Segment',
    'Country',
    'Region',
    'Category',
    'Sub-Category'
]

for col in categorical_cols:
    print(f"\n{col}")
    print(sales[col].value_counts())

for col in categorical_cols:
    sales[col] = sales[col].str.strip()

# All data seems to be consistant so no fixing needed.

Segment
Segment
Consumer       5191
Corporate      3020
Home Office    1783
Name: count, dtype: int64

Country
Country
United States    9994
Name: count, dtype: int64

Region
Region
West       3203
East       2848
Central    2323
South      1620
Name: count, dtype: int64

Category
Category
Office Supplies    6026
Furniture          2121
Technology         1847
Name: count, dtype: int64

Sub-Category
Sub-Category
Binders        1523
Paper          1370
Furnishings     957
Phones          889
Storage         846
Art             796
Accessories     775
Chairs          617
Appliances      466
Labels          364
Tables          319
Envelopes       254
Bookcases       228
Fasteners       217
Supplies        190
Machines        115
Copiers          68
Name: count, dtype: int64

Validate Numeric Columns for Invalid Negative Values

In [69]:
print("Negative Values in dataset:")

print("In Quantity Column:", (sales['Quantity'] <= 0).sum())

print("In Sales Column:", (sales['Sales'] < 0).sum())

print("In Profit Column:", (sales['Profit'] < 0).sum())

# Profit has 1871 negative values

Negative Values in dataset:
In Quantity Column: 0
In Sales Column: 0
In Profit Column: 1871

Checking Negative Profit

In [70]:
sales[sales['Profit'] < 0]

,Row ID,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Country,City,...,Postal Code,Region,Product ID,Category,Sub-Category,Product Name,Sales,Quantity,Discount,Profit
4800,355,CA-2016-138520,NaT,NaT,Standard Class,JL-15505,Jeremy Lonsdale,Consumer,United States,New York City,...,10035,East,FUR-BO-10002268,Furniture,Bookcases,Sauder Barrister Bookcases,388.704,6,0.2,-4.8588
4802,709,CA-2014-112158,NaT,NaT,First Class,DP-13165,David Philippe,Consumer,United States,New York City,...,10035,East,FUR-BO-10003272,Furniture,Bookcases,O'Sullivan Living Dimensions 5-Shelf Bookcases,883.920,5,0.2,-110.4900
4809,1861,US-2017-121251,NaT,NaT,First Class,GM-14440,Gary McGarr,Consumer,United States,New York City,...,10009,East,FUR-BO-10001918,Furniture,Bookcases,"Sauder Forest Hills Library with Doors, Woodla...",257.568,2,0.2,-28.9764
4810,1876,US-2016-112977,NaT,NaT,Standard Class,CJ-12010,Caroline Jumper,Consumer,United States,Long Beach,...,11561,East,FUR-BO-10003272,Furniture,Bookcases,O'Sullivan Living Dimensions 5-Shelf Bookcases,176.784,1,0.2,-22.0980
4813,2472,US-2016-135923,NaT,NaT,Standard Class,CM-11935,Carlos Meador,Consumer,United States,Fayetteville,...,28314,South,FUR-BO-10002213,Furniture,Bookcases,"Sauder Forest Hills Library, Woodland Oak Finish",451.136,4,0.2,-67.6704
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9989,9780,CA-2014-169019,NaT,NaT,Standard Class,LF-17185,Luke Foster,Consumer,United States,San Antonio,...,78207,Central,OFF-AP-10003281,Office Supplies,Appliances,Acco 6 Outlet Guardian Standard Surge Suppressor,4.836,2,0.8,-12.0900
9990,9832,CA-2014-113257,NaT,NaT,Second Class,SC-20305,Sean Christensen,Consumer,United States,Beaumont,...,77705,Central,FUR-FU-10001706,Furniture,Furnishings,Longer-Life Soft White Bulbs,8.624,7,0.6,-2.5872
9991,9835,CA-2016-126627,NaT,NaT,First Class,WB-21850,William Brown,Consumer,United States,La Porte,...,77571,Central,FUR-FU-10004963,Furniture,Furnishings,"Eldon 400 Class Desk Accessories, Black Carbon",14.000,4,0.6,-6.3000
9992,9904,CA-2014-122609,NaT,NaT,Standard Class,DP-13000,Darren Powers,Consumer,United States,Carrollton,...,75007,Central,FUR-FU-10004587,Furniture,Furnishings,"GE General Use Halogen Bulbs, 100 Watts, 1 Bul...",25.128,3,0.6,-6.9102
9993,9920,CA-2016-149272,NaT,NaT,Standard Class,MY-18295,Muhammed Yedwab,Corporate,United States,Bryan,...,77803,Central,FUR-CH-10000863,Furniture,Chairs,Novimex Swivel Fabric Task Chair,528.430,5,0.3,-143.4310

Checking Discounts

In [71]:
sales['Discount'].describe()
sales['Discount'].value_counts().sort_index()

sales[
    (sales['Discount'] < 0) |
    (sales['Discount'] > 1)
]

# Discount seems okay but some are on higher side like 70% and 80%

Empty DataFrame
Columns: [Row ID, Order ID, Order Date, Ship Date, Ship Mode, Customer ID, Customer Name, Segment, Country, City, State, Postal Code, Region, Product ID, Category, Sub-Category, Product Name, Sales, Quantity, Discount, Profit]
Index: []

[0 rows x 21 columns]

Verify Unique IDs

In [72]:
sales['Customer ID'].nunique() # 793

sales['Order ID'].nunique()  # 5009

sales['Row ID'].is_unique  # True

sales[sales['Row ID'].duplicated()] # No Duplicate Row id

Empty DataFrame
Columns: [Row ID, Order ID, Order Date, Ship Date, Ship Mode, Customer ID, Customer Name, Segment, Country, City, State, Postal Code, Region, Product ID, Category, Sub-Category, Product Name, Sales, Quantity, Discount, Profit]
Index: []

[0 rows x 21 columns]

In [73]:
clean_sales = sales.copy()
clean_sales.to_csv(r'D:\Data Analytics Projects\Retail Sales Analytics\Data\Cleaned Data\Clean_Sales_csv.csv', index=False)

In [74]:
print("Dataset Shape :", sales.shape)
print("Duplicate Rows :", sales.duplicated().sum())
print("Missing Values :", sales.isna().sum().sum())
print("Date Columns :", sales[['Order Date','Ship Date']].dtypes.tolist())

Dataset Shape : (9994, 21)
Duplicate Rows : 0
Missing Values : 19988
Date Columns : [dtype('<M8[s]'), dtype('<M8[s]')]

## Observation
| Check             | Result                     |
| ----------------- | -------------------------- |
| Duplicate rows    | 0                          |
| Missing values    | None                       |
| Date conversion   | Successful                 |
| Category names    | Consistent                 |
| Negative Quantity | None                       |
| Negative Profit   | 1871 (Valid business case) |
| Invalid Discounts | None                       |
| Unique IDs        | Verified                   |